### ISSUE TITLE
Support for vagrant-libvirt

### ISSUE THREAD

**Issue by phinze** [vagrant-landrush/landrush#20]
https://github.com/pradels/vagrant-libvirt

**Comment by fatmcgav** [comment]
Did this get anywhere?

**Comment by purpleidea** [comment]
In the very near future, I'll likely be patching vagrant-hostmanager (to fix some things) and then do the work to integrate with oh-my-vagrant, see: https://github.com/purpleidea/oh-my-vagrant/issues/68

If this landrush issues is fixed really soon, I might reconsider. So if someone is interested, do this now, because it will get it into the hands of a bunch of people. If not, it could still be a proposed feature to oh-my-vagrant eventually, but I doubt I'll write it.

**Comment by babilen** [comment]
What is needed to get support for this?

**Comment by sciurus** [comment]
FYI I'm no longer intending to work on this.

**Comment by babilen** [comment]
@sciurus Ah, good to know. What would you recommend instead?

**Comment by sciurus** [comment]
@babilen I've stopped doing development related to vagrant-libvirt due to changing personal and career circumstances. That's not a reflection on the merits of adding vagrant-libvirt support to landrush.

**Comment by strzibny** [comment]
This is my PR https://github.com/phinze/landrush/pull/124, can you look, test and report if you experience the same things as me?

**Comment by njam** [comment]
@strzibny @phinze is this one closeable (via https://github.com/vagrant-landrush/landrush/pull/138) ?

**Comment by phinze** [comment]
Yep seems like we can call this done!
