### ISSUE TITLE
Add command to clear all entries at once

### ISSUE THREAD

**Issue by ezekg** [vagrant-landrush/landrush#262]
I've had multiple instances where a virtual machine fails somehow (be it testing provisioning scripts, random errors, etc.) causing Landrush to leave hanging entries. Then in order to work with another virtual machine using the same tld/ip, I have to manually remove all of Landrush's entries.

Currently, you're forced to run `vagrant landrush ls`, grab the top-most entry and then `vagrant landrush rm $entry` tens of times to clean it all out.

Could we add a `vagrant landrush clean` command or something similar?

I'll do the PR if you don't have time.

**Comment by hferentschik** [comment]
Thanks, I like the idea. I have run into the "stale entries" issue myself several times. I think I'd prefer a flag for the `tm` command though. WDYT?

    landrush rm --all

That said, did you know you can at any stage just edit the configuration file which backs the host config. You find it in _~/.vagrant.d/data/landrush/hosts.json_. You can edit it with your favorite editor in order to clean it up or even delete it altogether between restarts. That's a bit easier than using `landrush rm` with a lot of entries.

> I'll do the PR if you don't have time.

If you have time, please send a pull request. Contributions are always welcome.

**Comment by ezekg** [comment]
Great. I like `landrush rm --all` better as well. I didn't think to look for a data file anywhere, so that's good to know. I'll work on putting together a pull request soon.

**Comment by hferentschik** [comment]
Fixed by pull request #287

**Comment by ezekg** [comment]
Hey, thanks for wrapping this up! Sorry I wasn't able to get to it.
