### ISSUE TITLE
Unable to connect to internet after installing landrush

### ISSUE THREAD

**Issue by ajaybhargov** [vagrant-landrush/landrush#91]
Hi,

I am not able to connect to internet after installing and enabling landrush in the vagrant file.

``` ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "precise64"

  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.landrush.enabled = true
  config.vm.hostname = "vagrantUpAndRunning.vagrant.dev"

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.customize ["modifyvm", :id, "--cpus", "2"]
  end

end
```

After enabling landrush, host command is working but it is taking lot of time to resolve the IP and sometimes it timesout too. I am not able to download anything from the internet if I enable landrush. If i disable, then I will be able to download from the internet but the host command stops working. 

Please advice and what needs to be done?

**Comment by thecederick** [comment]
Hi, this bug applicable for me too. VM's internet start working very slow when enabling landrush.

**Comment by hferentschik** [comment]
From which machine can you not reach the internet? From the host or from the VM or from both? I would assume from the VM, since only there all DNS is re-directed to Landrush. When the problem occurred, did you verify that Landrush was running `vagrant landrush status`? If not, make sure the Landrush server is actually running `vagrant landrush start`. 

Are you behind a firewall or other sort of network configuration (VPN) which would prevent you from using Google's DNS servers (8.8.8.8) as upstream servers for DNS queries? If you have a look at `~/.vagrant.d/data/landrush/config.json` and change the IPs to DNS server IPs which are valid in your network setup.
